title = "Devhunter"


[[menu.main]]
  name = "Discusiones"
  url = "http://devhunter.co/discusiones"

[[menu.main]]
  name = "Agenda"
  url = "http://devhunter.co/agenda"

[[menu.main]]
  name = "Sobre"
  url = "http://devhunter.co/sobre"


[params]
description = "Construyendo comunidad"
disqusShortname = "devhunterco"
contribURl = "https://github.com/devhunterco/blog#como-contribuir"
